### ISSUE TITLE
Series link not working against Tvheadend v4.4.x

### ISSUE THREAD

**Issue by cherowley** [jahutchi/script.tvheadend.apiutils#1]
trying to use the series link toggle but always says no series link?

Log:

16:34:30.243 T:3588  NOTICE: [script.tvheadend.apiutils] Tvheadend API response received:
16:34:30.243 T:3588  NOTICE: [script.tvheadend.apiutils] {"totalCount":1,"entries":[{"eventId":936036,"episodeUri":"crid://fp.bbc.co.uk/m/5QGZ","serieslinkUri":"crid://fp.bbc.co.uk/m/5LKU/02","channelName":"BBC TWO HD","channelUuid":"9580b748ea184c45768705abd142e97c","channelNumber":"2","channelIcon":"imagecache/242","start":1570032000,"stop":1570042800,"title":"World Athletics Championships","subtitle":"Gabby Logan presents live coverage from Doha.","summary":"Gabby Logan presents live coverage from Doha. Day one's hectic heptathlon schedule concludes with the fourth event - the 200m. [S] [HD]","widescreen":1,"subtitled":1,"hd":1,"genre":[64],"nextEventId":936079}]}
16:34:30.243 T:3588  NOTICE: [script.tvheadend.apiutils] Converting JSON response
16:34:30.243 T:3588  NOTICE: [script.tvheadend.apiutils] JSON Conversion Complete
16:34:30.243 T:3588  NOTICE: [script.tvheadend.apiutils] Series Link information was not availble for this event
16:34:30.245 T:3588 WARNING: [script.tvheadend.apiutils] No series link information was available for this event

**Comment by jahutchi** [comment]
A couple of questions

1) What version of Tvheadend are you using.
2) Do you see the record series button for this same show in the Tvheadend web interface

The plugin currently expects Tvheadend to return both the serieslinkUri and serieslinkId attributes before it'll attempt to set a series link. For this show your Tvheadend server only returned the serieslinkUri attribute.

**Comment by cherowley** [comment]
Hi!

I’m running 4.4.20181215

Series link button appears and works fine in kodi libreelec 18 😊

Series link button appears and works fine in tvh web interface.

I’ve removed the check  for the serieslinkId from your code and it seems to work ok?

**Comment by jahutchi** [comment]
All development/testing was done against my Tvheadend 4.2.x setup, so maybe something changed in 4.4

When I saw your message I tried series linking that very same show on Freeview and it worked (& in the log I can see both attributes were returned).

Are you on freeview or freesat? And which grabber do you use?

I'll dig into the Tvheadend/pvr.hts/kodi code further, and see which attributes those require before allowing a series link to be set.

In the meantime, your code tweak (to just check serieslinkUri) should do the trick.

**Comment by jahutchi** [comment]
@cherowley this should be resolved by 8997c9aa44a3dd4d088bd5af1041411b4e63ccd3

I'm guessing this is the same as the tweak you made yesterday to remove the check for serieslinkId ?

Are you able to verify this works against your Tvheadend v4.4.20181215 server? If so, then I'll cut a v1.0.5

Thanks

**Comment by cherowley** [comment]
Morning!

Yes that's exactly what I did, remove the additional check :)

I'll double check your version and report back later.

Thanks again for this - the wife has been bugging me for ages for a single record button press for series link in Kodi!

Cheers!

**Comment by jahutchi** [comment]
> the wife has been bugging me for ages for a single record button press for series link in Kodi!

I had the same nagging from my wife - was a deal breaker for moving from a crappy pvr recorder box to kodi. This is the primary reason I created this addon ;-)

**Comment by cherowley** [comment]
lol!

I rebuilt and tested with your revision and all is ok :)

**Comment by jahutchi** [comment]
v1.0.5 released, with this fix included
https://github.com/jahutchi/script.tvheadend.apiutils/releases/tag/v1.0.5
